This is the full note on Deep Learning for Computer vision 

In [2]:
import tensorflow as tf 


In [3]:
tensor_zero_d=tf.constant(23) # zero dimentional array ( fancy name of array is  tensor )
print(tensor_zero_d)

tf.Tensor(23, shape=(), dtype=int32)


In [4]:
#1d tensor  
tensor_1D=tf.constant([1,2,3,4])
print(tensor_1D)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [5]:
#2d tensor
tensor_2D=tf.constant([
                      [1,2,3,4],
                      [5,6,7,8],
                      [2,5,7,9]])
print(tensor_2D)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]
 [2 5 7 9]], shape=(3, 4), dtype=int32)


In [6]:
#3d tensor 
tensor_3D=tf.constant([
                       
                      [ [1,2,3,4],
                        [5,6,7,8],
                        [2,5,7,9]  ],
                     
                     [  [1,2,3,4],
                        [5,6,7,8],
                        [2,5,7,9]  ],
                      
                     [  [1,2,3,4],
                        [5,6,7,8],
                        [2,5,7,9]  ]
                                      ],dtype=tf.float32)


# Print the tensor
print(tensor_3D)


tf.Tensor(
[[[1. 2. 3. 4.]
  [5. 6. 7. 8.]
  [2. 5. 7. 9.]]

 [[1. 2. 3. 4.]
  [5. 6. 7. 8.]
  [2. 5. 7. 9.]]

 [[1. 2. 3. 4.]
  [5. 6. 7. 8.]
  [2. 5. 7. 9.]]], shape=(3, 3, 4), dtype=float32)


In [7]:
print(tensor_3D.shape)

(3, 3, 4)


Numpy arrary to Tensor


In [8]:
import numpy as np

np_array=np.array([1,2,3,4,5,6,6,7])

Tensor=tf.convert_to_tensor(np_array)
print(Tensor)


tf.Tensor([1 2 3 4 5 6 6 7], shape=(8,), dtype=int64)


In [9]:
# create an identity tensor using tensor flow 
Identity_Tensor=tf.eye(
    num_rows=4,
    num_columns=4,
    batch_shape=[5],
    dtype=tf.dtypes.float32,
    name="identity_tensor"
)
print(Identity_Tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(5, 4, 4), dtype=float32)


Tensor fill method 

In [10]:
Filled_Tensor=tf.fill(
    dims=[5,5], value=1, name="filled Tensor", layout=None
)

print(Filled_Tensor)



tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]], shape=(5, 5), dtype=int32)


one hot  operation 

In [11]:
One_hot_tensor=tf.one_hot(
    indices=[1,2,3,4],
    depth=5,
    on_value=1,
    off_value=0,
    axis=None,
    dtype=float,
    name=None
)
print(One_hot_tensor)

tf.Tensor(
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(4, 5), dtype=float32)


Numpy array Basics 


In [12]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [13]:

ones_array = np.ones((2, 4))
print("Ones Array:\n", ones_array)


Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
ones_array = np.eye( 4)
print("Ones Array:\n", ones_array)



Ones Array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Tensor flow 

In [21]:
# Creating a 3D tensor with shape (2, 3, 4)
tensor_3d = tf.constant([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])


print("Shape of the tensor:", tensor_3d.shape)
print(tf.expand_dims(tensor_3d,axis=1))

Shape of the tensor: (3, 3, 4)
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(3, 1, 3, 4), dtype=int32)


Training the first model (car price prediction )

In [2]:
import tensorflow as tf 
import pandas as pd 
import seaborn as sns 


In [3]:
data=pd.read_csv("used_cars.csv")
data.shape

(4009, 12)

Data set preparation 

In [4]:
data.info

<bound method DataFrame.info of          brand                            model  model_year      milage  \
0         Ford  Utility Police Interceptor Base        2013  51,000 mi.   
1      Hyundai                     Palisade SEL        2021  34,742 mi.   
2        Lexus                    RX 350 RX 350        2022  22,372 mi.   
3     INFINITI                 Q50 Hybrid Sport        2015  88,900 mi.   
4         Audi        Q3 45 S line Premium Plus        2021   9,835 mi.   
...        ...                              ...         ...         ...   
4004   Bentley             Continental GT Speed        2023     714 mi.   
4005      Audi             S4 3.0T Premium Plus        2022  10,900 mi.   
4006   Porsche                           Taycan        2022   2,116 mi.   
4007      Ford                     F-150 Raptor        2020  33,000 mi.   
4008       BMW                     X3 xDrive30i        2020  43,000 mi.   

          fuel_type                                             eng

In [5]:
data.isnull().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [7]:
data.duplicated().sum()

np.int64(0)